import Head from 'next/head'
import styles, {globalStyles} from './styles';


export default function AppLayout({ children }) {
    return (
        <>
            <Head>
                <title>Twitter Clone 🐦</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <main>
                    {children} 
                </main>
            </div>

            <style jsx>{styles}</style>
            <style jsx global>{globalStyles}</style>
        </>
    )
}